/*(1) write a 5 prograns using cin and cin and count.
   (II) Wirte a c program to enter length and breadth of a rectangle and find
    its perimeter and area.*/
#include<iostream>
using namespace std;
int main()
{
	int length,breath;
	cout<<"Enter a lenth of Rectangle :: ";
	cin>>length;
	cout<<"Enter a breath of Rectangle :: ";
	cin>>breath;
	cout<<"paramiter of rectangle is :: "<<length+length+breath+breath<<endl;
	cout<<"area of rectangle is :: "<<length*breath<<endl;
	
	cout<<"Student Name  :: Dholariya Ayush Prafulbhai"<<endl;
    cout<<"Enrollment no :: 220130318022";
	return 0;
}
