/*(1) write a 5 prograns using cin and cin and count.
	(IV) Wirte a c program to enter radius of a circle and find its diameter,
	circumference and area */
#include<iostream>
using namespace std;
int main()
{
	int radius;
	cout<<"Enter a radius of circle :: ";
	cin>>radius;
	cout<<"dia of circle is :: "<<2*radius<<endl;
	cout<<"circumference of circle is :: "<<2*3.14*radius<<endl;
	cout<<"area of circle is :: "<<3.14*radius*radius<<endl;
	
	cout<<"Student Name  :: Dholariya Ayush Prafulbhai"<<endl;
    cout<<"Enrollment no :: 220130318022";
	return 0;
}
