/*(1) write a 5 prograns using cin and cin and count.
	(I) Wirte a c program to enter two numbers and finmd their sum.*/
#include<iostream>
using namespace std;
int main()
{
	int num1,num2;
	cout<<"Enter a number 1 value :: ";
	cin>>num1;
	cout<<"Enter a number 2 value :: ";
	cin>>num2;

	cout<<"Sum of two number is :: "<<endl;
	cout<<num1+num2;
	
	cout<<"Student Name  :: Dholariya Ayush Prafulbhai"<<endl;
    	cout<<"Enrollment no :: 220130318022";

	return 0;
}
